### ISSUE TITLE
email doesn't exist

### ISSUE THREAD

**Issue by Fandekasp** [DarkSpiritz/DarkSpiritz#10]
![](https://i.imgur.com/PWCFHkE.png)

**Comment by Ryan0x1** [comment]
Ah try to forward us an email at syndicatedintel@protonmail.com! it's all over our website lol

**Comment by Fandekasp** [comment]
@Ryan0x1 what I meant is, you probably want to fix the README :+1: 	
![](https://i.imgur.com/4XOkbYP.png)

Thanks

**Comment by Ryan0x1** [comment]
Ah ok, i'll get it done now thanks :+1:
