### ISSUE TITLE
Can't create user

### ISSUE THREAD

**Issue by opabravo** [DarkSpiritz/DarkSpiritz#13]
Welcome to the DarkSpiritz Penetration Testing Framework.
In order to start you must create a default user config.
All it requires from you is a username you'd like to use.
()
Enter Username: root
Traceback (most recent call last):
  File "start.py", line 65, in <module>
    checkdat()
  File "start.py", line 63, in checkdat
    startup.createdat()
  File "/home/opabravo/DarkSpiritz/config/startup.py", line 28, in createdat
    name = input("Enter Username: ")
  File "<string>", line 1, in <module>
NameError: name 'root' is not defined

**Comment by Polibus** [comment]
Hi i have the exact problem on Ubuntu 18.04 python version:3.6.6 and 2.7.15rc1

**Comment by Polibus** [comment]
hi M4cs the config file created when i instert the username with "" is differnt is like this 
```
[DEFAULT]
lastrun = 
lhost = 0.0.0.0
lport = 8080
version = 
name = root
userlist = /usr/bin/wordlist.txt
urlpath = /connect
passlist = /usr/bin/passlist.txt
platform = linux2
rhost = 
interface = wlan0
rport = 

```

**Comment by M4cs** [comment]
So it practically the same but in a different order.. this is so weird. It generates the config file and then breaks for you?

**Comment by M4cs** [comment]
wait are you running this in python2? Try using the command python3 start.py instead of python

**Comment by Polibus** [comment]
no but it gave me an error after i changed the config file (when lunched ./start.py)
the error was `ModuleNotFoundError: No module named 'terminaltables'` installed with pip3 and works fine

**Comment by M4cs** [comment]
ok so now that you have terminaltables installed its working?

**Comment by Polibus** [comment]
after i modified the userdat.ini like you tell and after i have installed terminaltables

**Comment by M4cs** [comment]
I was confused given normally python3.3+ should only return linux not linux2.

**Comment by Polibus** [comment]
maybe i lunched python (by default on my machine ) instead of python3 .
Thanks for your help

**Comment by M4cs** [comment]
Yeah i believe that was the issue. If you arent working with python2 anymore i recommend changing aliases in your ~/.bashrc

**Comment by M4cs** [comment]
@opabravo I'm closing this issue. If the fixes above dont work please let me know and we can debug.

**Comment by Polibus** [comment]
good advice , but i came from kitploit where is not specified to run it with python3

**Comment by M4cs** [comment]
Ah DS used to be written in Python 2 but we recently updated it. Should say that in the readme.
