### ISSUE TITLE
Stick with 'python-whois' instead of 'whois'

### ISSUE THREAD

**Issue by noptrix** [DarkSpiritz/DarkSpiritz#14]
Hi.

I've packaged darkspiritz for BlackArch Linux. I've removed the library 'whois' since you are not using it yet in your code. If you start using it I've to freeze the package because of conflicts with 'python-whois' library.
If possible can you stick with 'python-whois' library rather than the old 'whois'? The point is that both are in conflict and install same files in same directory. Also, 'whois' seems to be old and not developed anymore. Slowly becoming obsolete.

Cheers,
noptrix

**Comment by M4cs** [comment]
Since we dont use any whois in here I've removed it form the requirements.
