### ISSUE TITLE
Install script breaks dependency manager

### ISSUE THREAD

**Issue by etaoin** [DarkSpiritz/DarkSpiritz#5]
The two lines of install script:

print Command_exe("["+time.strftime('%H:%M:%S')+"] Making python2 as default.                 ",'mv /usr/bin/python2 /usr/bin/python')
print Command_exe("["+time.strftime('%H:%M:%S')+"] Fixing python3.                 ",'mv /usr/bin/python3 /usr/bin/python3')

Caused my package manager to freak out(dpkg fails to execute some post-inst/pre-inst scripts):

Unpacking python3-apt (1.7.0~rc1) over (1.6.2) ...
Preparing to unpack .../18-python-apt_1.7.0~rc1_amd64.deb ...
/var/lib/dpkg/info/python-apt.prerm: 6: /var/lib/dpkg/info/python-apt.prerm: pyclean: not found
dpkg: warning: old python-apt package pre-removal script subprocess returned error exit status 127
dpkg: trying script from the new package instead ...
/var/lib/dpkg/tmp.ci/prerm: 6: /var/lib/dpkg/tmp.ci/prerm: pyclean: not found
dpkg: error processing archive /tmp/apt-dpkg-install-6IXmyH/18-python-apt_1.7.0~rc1_amd64.deb (--unpack):
 new python-apt package pre-removal script subprocess returned error exit status 127
/var/lib/dpkg/info/python-apt.postinst: 6: /var/lib/dpkg/info/python-apt.postinst: pycompile: not found
dpkg: error while cleaning up:
 installed python-apt package post-installation script subprocess returned error exit status 127

My python environment is a mess, so this can be my mistake, but I think installation script shouldn't move my python binaries around or change my default environment.

**Comment by M4cs** [comment]
Thank you for mentioning this. I didn’t experience this on Ubuntu or Kali it my Debian WSL it Kali WSL so it may be a localized problem however as long as you have python 2 as your default environment those lines of code aren’t necessary. I’ll clean it up soon :)

**Comment by M4cs** [comment]
I have fixed the issue. You can either just delete those lines or comment them out or re-download the repository!
